In [1]:
import  tensorflow as tf
import numpy as np
W = tf.Variable(tf.random_normal([3,2]), name='W')
b = tf.Variable(tf.random_normal([1,2]), name='b')
X = tf.placeholder('float',[None,3], name='X')
y = tf.nn.sigmoid(tf.matmul(X,W)+b, 'y')

In [2]:
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    X_array = np.array([[0.4,0.2,0.4],[0.3,0.4,0.5],[0.3,-0.4,0.5]])
    (_b,_W,_X,_y) = sess.run((b,W,X,y), feed_dict={X:X_array})

In [3]:
print _b

[[ 0.90936011  2.46674442]]


In [4]:
print _W

[[-0.67379773  0.76830679]
 [-0.69151038  1.05369365]
 [-0.05262351 -0.36655471]]


In [5]:
print _X

[[ 0.40000001  0.2         0.40000001]
 [ 0.30000001  0.40000001  0.5       ]
 [ 0.30000001 -0.40000001  0.5       ]]


In [6]:
print _y

[[ 0.61786348  0.94470465]
 [ 0.59972149  0.94957066]
 [ 0.72262359  0.89017028]]


In [7]:
ts_c = tf.constant(2, name='ts_c')
ts_x = tf.Variable(ts_c+5, name='ts_x')

In [8]:
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('ts_c=', sess.run(ts_c))
    print('ts_x=', sess.run(ts_x))

('ts_c=', 2)
('ts_x=', 7)


## 执行"计算图"

In [9]:
#建立session
sess = tf.Session()

In [10]:
#使用session初始化变量
init = tf.global_variables_initializer()
sess.run(init)

In [11]:
#使用sess.run显示tf常数
print('ts_c', sess.run(ts_c))

('ts_c', 2)


In [12]:
#使用sess.run显示tensorflow变量
print('ts_x=', sess.run(ts_x))

('ts_x=', 7)


In [13]:
#使用.eval()方法显示TF常数
print('ts_c=', ts_c.eval(session=sess))

('ts_c=', 2)


In [14]:
#使用eval()方法显示tf变量
print('ts_x', ts_x.eval(session=sess))

('ts_x', 7)


In [15]:
#关闭TensorFlow Session
sess.close()

## TensorFlow placeholder
如果希望在执行计算图阶段才设置数值,那么就必须使用placeholder

In [17]:
width = tf.placeholder('int32')
height = tf.placeholder('int32')
area = tf.multiply(width, height)
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('area=', sess.run(area, feed_dict={width:6, height:8}))

('area=', 48)


## TensorFlow 数值运算方法介绍
更多内容请参阅:https://www.tensorFlow.org/api_docs/python/math_ops/

## TensorBoard
可视化的方式查看所建立的'计算图'

In [19]:
import tensorflow as tf
width = tf.placeholder('int32', name='width')
height = tf.placeholder('int32', name='height')
area = tf.multiply(width, height, name='area')

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('area=', sess.run(area, feed_dict={width:6, height:8}))

('area=', 48)


In [21]:
tf.summary.merge_all()
train_writer = tf.summary.FileWriter('log/area', sess.graph)

## 建立一维与二维张量
零维张量对应为标量

In [22]:
ts_X = tf.Variable([0.4,0.2,0.4])

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    X = sess.run(ts_X)
    print(X)

[ 0.40000001  0.2         0.40000001]


In [23]:
print(X.shape)

(3,)


In [24]:
ts_X = tf.Variable([[0.4,0.2,0.4]])

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    X = sess.run(ts_X)
    print(X)
    print(X.shape)

[[ 0.40000001  0.2         0.40000001]]
(1, 3)


## 矩阵基本运算

In [25]:
X = tf.Variable([[1.,1.,1.]])
W = tf.Variable([[-0.5,-0.2],[-0.3,0.4],[-0.5,0.2]])
XW = tf.matmul(X,W)

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    result = sess.run(XW)
    print(result)

[[-1.29999995  0.40000001]]


In [26]:
#加法
b = tf.Variable([[0.1,0.2]])
XW = tf.Variable([[-1.3,0.4]])

Sum = XW+b

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('sum:')
    print(sess.run(Sum))

sum:
[[-1.19999993  0.60000002]]
